apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-basic
  title: Python Basic Project
  description: A simple template for a Python project.
  tags:
    - Python
    - GoldenPath
spec:
  owner: team-backend
  path: ./template
  schema:
    required:
      - name
    properties:
      name:
        title: Project Name
        description: The name of the Python project
        type: string
  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:plain
      input:
        url: https://github.com/sh1ntar0/backstage-templates/python-basic-template.git
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com/sh1ntar0/{{ parameters.name }}
        description: A simple Python project
        defaultBranch: main
    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/sh1ntar0/{{ parameters.name }}/blob/main/catalog-info.yaml
